### ISSUE TITLE
Undoing shutup.please()

### ISSUE THREAD

**Issue by ErykPiasecki07** [polvoazul/shutup#2]
Sometimes the annoying warnings come up in specific moments of the program's execution. After those moments maybe some warnings would actually be **helpful**.

It would be really useful to have a function in this library that would be able to undo all the shut-uping. 

Sort of 'Python, I've changed, please come back to me' type thing ;)

**Comment by sinwoobang** [comment]
Looking forward to the name of this method.

**Comment by ErykPiasecki07** [comment]
Hmmm, can't figure out anything creative. Maybe `shutup.sorry()`?

**Comment by polvoazul** [comment]
Sorry for the late reply!
Yeah, I think this functionality makes perfect sense, and its pretty easy to implement.
The only problem is how to name the method!

**Comment by polvoazul** [comment]
Maybe leave this open for a bit to collect suggestions?

I like "sorry" btw. 

I will try to think of other options in the meantime

**Comment by polvoazul** [comment]
It makes sense to create a funny-name function, but i also feel inclined to create well named aliases such as:

    shutup.mute_warnings()
    shutup.unmute_warnings()

I think that the joke works in the top of the file, out of sight. But if we have a context manager with `shutup.sorry()` in the middle of the code, it can get quite confusing.

**Comment by polvoazul** [comment]
shutup.what_is_it()
shutup.tell_me()
shutup.not_really()
shutup.jk()

**Comment by ErykPiasecki07** [comment]
shutup.jk() sounds the best for me, the aliases would also work great if the code is ever used on production. Looking forward to see this issue implemented!

**Comment by polvoazul** [comment]
I've implemented the feature (+ context managers) in this branch:

https://github.com/polvoazul/shutup/tree/unmuting

If you want to test it, install directly from github: `pip install git+https://github.com/polvoazul/shutup@unmuting`. Docs are on the branch's README.

I'll wait a bit before merging to master.

If you have any issues/suggestions, please comment
