### ISSUE TITLE
Cannot remove `DepecrationWarning`

### ISSUE THREAD

**Issue by jpmvferreira** [polvoazul/shutup#6]
Hi there,

I made my own Python package which is composed of two scripts and a standard Python package with several folders.
Here's the content of the `setup.py`:
```python
from setuptools import setup

with open(f"README.md") as f:
    long_description = f.read()

setup(name="stag",
      version="0.0.0",
      description="A CLI that simplifies the usage of MCMC methods.",
      scripts=["bin/stag", "bin/stag-fs"],
      packages=["stag"],
      long_description=long_description,
      long_description_content_type="text/markdown",
      install_requires=["click"],
      url="https://github.com/jpmvferreira/stag",
      author="José Ferreira",
      author_email="jose@jpferreira.me",
      license="MIT",
      zip_safe=False
)
```

Every time I run one of the binaries, I always get the following message:
```
/home/undercover/.micromamba/envs/stag/bin/stag:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('stag==0.0.0')
```

I can't for the sake of anything turn it off, which is really annoying, especially because I'm not using anything that is non standard here. 
My CLI utility depends on a single package, `click`, and then uses Python built-in `sys` and `os` packages, nothing else.

Trying to suppress warnings doesn't cut it as well.
What to do?
Do you happen to know what is causing this deprecation warning anyways, and how it can be solved (either by shutting it up or by actually fixing it)?

**Comment by polvoazul** [comment]
Hum... it seems like your warning is being emited by the scripts themselves. Are you using pkg_resources there? The replacement is https://docs.python.org/3/library/importlib.resources.html

Can you post the head of your 'stag' file here so that i can have more information?

Also, have you tried using shutup.please in the top of your script files?

**Comment by polvoazul** [comment]
Also, how are you installing this package? via `pip install .` or `python setup.py install`? try using `pip install .` or `pip install -e .`

**Comment by jpmvferreira** [comment]
It was a local package, and I was using a deprecated method for installing it.
I was using a standard `setup.py` and then installing it via `pip install -e .`.
Now that I am using the correct approach the problem is solved, but because I thought this package would catch all errors I decided to report this anyways.
Would you like me to try and replicate my setup or do you think that this is something not worth taking into account?

**Comment by polvoazul** [comment]
Nahh, I don't think we need to give you extra work with this. Its fine.
