### ISSUE TITLE
Deprecation warnings from torchvision still appear

### ISSUE THREAD

**Issue by wl2776** [polvoazul/shutup#7]
Python 3.9 installed in a virtual environment.
Torchvision 0.14.1

Warnings:

```
/home/user/.env/py39pytorch/lib/python3.9/site-packages/torchvision-0.14.1-py3.9-linux-x86_64.egg/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(msg)

/home/user/.env/py39pytorch/lib/python3.9/site-packages/torchvision-0.14.1-py3.9-linux-x86_64.egg/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
```

Head of file that emits these warnings

```py
#!/usr/bin/env python3

import sys
import argparse
from pathlib import Path

import shutup ; shutup.please()

import numpy as np
import torch.cuda
from joblib import Parallel, delayed
from tqdm_joblib import tqdm_joblib

from scipy.spatial.distance import jensenshannon

# other imports of local modules
# other code
```

moving call to `shutup.please()` to the end of imports does not help, the following code still produces warnings:

```py
#!/usr/bin/env python3

import sys
import argparse
from pathlib import Path

import numpy as np
import torch.cuda
from joblib import Parallel, delayed
from tqdm_joblib import tqdm_joblib

from scipy.spatial.distance import jensenshannon

# other imports of local modules

import shutup ; shutup.please()

# other code
```

**Comment by polvoazul** [comment]
I cant reproduce it :/ I installed python3.9, torchvision 0.14.1 and ran the above script and got no warnings.

Can you send me your 'pip freeze' so that i can install all dependencies with correct versions?

Even better, if you can, wrap your example in a docker container.

**Comment by polvoazul** [comment]
I took a look at the code that is emmiting the warning and it should have been muted by shutup. Is this file your entry point? I mean, are you calling your script from this file? Is there a chance that torch is being imported through other file before shutup.please is called?

**Comment by wl2776** [comment]
The problem was in using joblib module.
It seems, that joblib does not execute code from all modules when spawns new processes.

It is required to move call to `shutup.please` inside the function that is being parallelized.

**Comment by polvoazul** [comment]
Makes sense! I'm glad you found the culprit. Enjoy the silence!
