### ISSUE TITLE
NumpyWarning

### ISSUE THREAD

**Issue by wyhh1** [polvoazul/shutup#8]
I've put ‘import shutup’ 'shutup.please' in the first line but it's still warning.

DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  F_table[t, item] = optimizer.gbest_F

**Comment by polvoazul** [comment]
Can you send me a minimum example script so that i can take a look? also send `pip freeze` and your python version so that i can install requirements in the same version as you.

also, are you using `shutup.please()` or `shutup.please`?

**Comment by wyhh1** [comment]
sorry but i forget what the used script was like, environment is Anaconda Python==3.9,NUMPY==1.2.5.
and i solved the problem by  adding the following script:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

**Comment by polvoazul** [comment]
Im happy that you solved it! I'm closing this issue as I can't investigate without reproducing. See ya!
